"""Maps between model names and more readable versions.

Model/code names (on the left) are used internally by Cavecalc. Readable names
are largely used in the GUI. Conversion between them is handled by the
setter.NameSwitcher class.
"""

database =         "PHREEQC Database Filename"
phreeqc_log_file =     "Log PHREEQC input"
phreeqc_log_file_name = "PHREEQC Log Filename"
out_dir =              "Output Directory"
temperature =          "Temperature (Degrees C)"
co2_decrement =        "CO2(g) removal per step (fraction)"
calcite_sat_limit =    "Calcite supersaturation limit (SI)"
bedrock =              "Bedrock (moles)"
bedrock_mineral =      "Bedrock Lithology"
bedrock_pyrite =       "Bedrock Pyrite (moles)"
bedrock_d44Ca =        "Bedrock d44Ca (per mil)"
bedrock_d13C =         "Bedrock d13C (per mil)"
bedrock_d18O =         "Bedrock d18O (per mil)"
bedrock_MgCa =         "Bedrock Mg/Ca (mmol/mol)"
bedrock_SrCa =         "Bedrock Sr/Ca (mmol/mol)"
bedrock_BaCa =         "Bedrock Ba/Ca (mmol/mol)"
atmo_exchange =		"Second Gas Fraction (0-1)"
gas_volume =		"Gas Volume (L)"
atm_O2 =        "Second Gas O2 (%)"
atm_pCO2 =		"Second Gas pCO2 (ppmv)"
atm_d13C =		"Second Gas d13C (per mil)"
atm_R14C =		"Second Gas R14C (pmc)"
atm_d18O =		"Rainfall d18O (per mil)"
init_O2 =       "Initial O2 (%)"
init_pCO2 =		"Initial pCO2 (ppmv)"
init_d13C =		"Initial d13C (per mil)"
init_R14C =		"Initial R14C (pmc)"
init_solution_d13c = "Initial Solution d13C (per mil) - OVERWRITE"
cave_O2 =       "Cave Air O2 (%)"
cave_pCO2 =		"Cave Air pCO2 (ppmv)"
cave_d13C =		"Cave Air d13C (per mil)"
cave_R14C =		"Cave Air R14C (pmc)"
cave_d18O =		"Cave Air d18O (per mil)"
cave_air_volume = "Cave Air Volume (L)"
soil_pH =       "Soil pH (approx.)"
soil_O2 =       "Soil Gas O2 (%)"
soil_pCO2 =     "Soil Gas pCO2 (ppmv)"
soil_Ca =       "Soil Ca (mmol/kgw)"
soil_Mg =       "Soil Mg (mmol/kgw)"
soil_Sr =       "Soil Sr (mmol/kgw)"
soil_Ba =       "Soil Ba (mmol/kgw)"
soil_d13C =     "Soil Gas d13C (per mil)"
soil_R14C =     "Soil Gas R14C (pmc)"
soil_d44Ca =    "Soil d44Ca (per mil)"
kinetics_mode =        "Degassing/Precipitation Mode"
reprecip =             "Allow Calcite Reprecipitation"
totals =       "Totals"
molalities =   "Molalities"
isotopes =      "Isotopes"
